[google_service_account]
type = "service_account"
project_id = "trim-sunlight-420806"
private_key_id = "fb84c0eea6e35a89a2435c7adbd5bf49c95869d4"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGtkbYCBRMiKya
JKI3VUA3Hmd7OpruHw5EYIXmLJIN6uSQqJ95+71rbawueEkhV2HDG2TY6TKfkAfd
LzW1JIIzTozHjU4ewDMXfatPnUpJrQkAteFBRPG8oF93qo7/Lm2zi9cJ2nB7WpDU
gfR7pnBNL3vRjQGeYMxHjCSYpcJkuGCyJpZIvN3FmDS+aJYZUcqX8uNHt/R0NVlU
Lqj38wjDyeFCuYr25RxTFKX+oFXGH3uh/TPX9z/Y18nhUvGebfc2O4ZQAr/mAOFr
bIKLCn8AGxkSJnH1fMbFFurZQ4Lx7yiHqtVWdOL2XyqNdYN7McQd4qje0f412rwo
oxJoMcTTAgMBAAECggEABPviwcSwFjzK61EGUgxsucf9hXOfnnELsr/syZ1F3Ln0
sYgWOQnKnO+Lz+mnWv0ZTYH1SIkoKaXHL18Qb56QKpxyB5f/bJJ+fBSsLTU2iw9E
fAA+peQ1GrNxlMMnUzhBMBlbtVjy5xLCClAHNDlDgmI1Wdq2VUkOMGog7dIuz6cX
k2HjIwIz6zJ2Mvac9swkZ/pCVzOeNjXmHOZUoWk8yu4EaqpFEOpyV+++PAYs6VJX
fHjbnYyAN7IfCsnn75vQYUnUlK17ktdUbODcoYk36ZP8XeScnhzQnJrqWF5rqeyd
/ciXpKDvHroDNrovKkrKCC35jYztSha7xQ9TXNFM0QKBgQC+EPj2w4XYS2RRoT3L
nQfI1sj77G/uoXu7UjuympYDG/eafyf1zJxGdoSSQQWslI416+pepMdzV1rATzPG
tOoy7cfHhEgAj46fI7vUVRC4QbyGg3PVdNvLy7SUQouAKkijxR4rTbTV6HUSWr/o
Qdvju3VDn6Ma9+izLU3KhdrtxQKBgQC1cYMW36mVw9vBUXMoO9aDrXSNLS6IsSNy
NmlValQhuPsZksm1xTBZKh7yMLcRs7kGxOOX63MLM1KEBQj9SCRkgn/vqV+jpCEb
5ZMZXojux8/nCRGms9xPpDHPqSZgE9nFDU9Yv450R0006JWXX2uFjW745l+l5b9M
7X3rlzxptwKBgEJoR7RgKDmkTc6/mYm0ue2QLfTnbUxhG4wddUI4BMXdVaujVeDp
tohgDH3VPhhIZ0+rt92NkSpZkRm0EpEQ0OsubSjmrQmVHu23XH8ZoZffT/FnqGci
R1FzQQq0HW2QWITv8FSM9+vtJkpdbsPFjwCIlLYl5qUbjTBdWdqy3gVJAoGATFF4
oDBntnTxhDjsRSoWKsDU22T7w8cub6XvXFwjEyQpijIx4eEVWwvahGh1OF7uHqjG
Smpgs39c3+b2RwMHO7egdIA7mCs7Oe6wluUql7U3/6fS4tmYe29G/F/bomH3IWld
zKiWFNbA5NZHxan/IefBm7Pa237tnj/uzR+J67UCgYEAjcQM0wUnZPlC2w7Cj1aK
6Gwz6My/gIV2w34fcdyxA4zi+s0VoKcUSE9o4HfBrVDYvDzV0elpHDi7BS45emxY
akqWFrEod7AOuWG85F6/1mLm8vrL3BDxd59BGjRuGW4ZlxdzBTtLHNMq97LSQ/wG
pkoJX7YPs9BrqjWs3bIRpXw=
-----END PRIVATE KEY-----
"""
client_email = "todolist@trim-sunlight-420806.iam.gserviceaccount.com"
client_id = "111073269977826265352"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/todolist%40trim-sunlight-420806.iam.gserviceaccount.com"
universe_domain = "googleapis.com"